DELETE FROM CURRENCY;
INSERT INTO CURRENCY (ID, RATE) VALUES ('eur', 1.0);
INSERT INTO CURRENCY (ID, RATE) VALUES ('sek', 9.27);
INSERT INTO CURRENCY (ID, RATE) VALUES ('usd', 1.10);
INSERT INTO CURRENCY (ID, RATE) VALUES ('czk', 27.03);
